# This playbook is to be run on the server machine, allowing TLS-Auth key exchanging and certificate signing.
---
  - name: "Signing certificates and exchanging keys"
    hosts: all
    connection: ssh
    become: yes

    vars_prompt:
    - name: server_ip
      prompt: "What is the IP address of the server?"
      private: false

    tasks:
      - import_tasks: tasks/crt-key-exchange.yaml
      - import_tasks: tasks/openvpn.yaml