---
  - name: "TESTING PI"
    hosts: all
    connection: ssh
    become: yes

    vars_prompt:
      - name: nas
        prompt: "Enter NAS IP and target directory"
        private: no
    
    tasks:
      - import_tasks: tasks/update.yaml
      - import_tasks: tasks/install-sys-utils.yaml
      - import_tasks: tasks/install-py-utils.yaml
      - import_tasks: tasks/hostname.yaml
      - import_tasks: tasks/filesystem.yaml
      - import_tasks: tasks/testbed.yaml
      - import_tasks: tasks/setup.yaml
      - import_tasks: tasks/services.yaml
      - import_tasks: tasks/reboot.yaml
