---
  - name: "Configuring Pi's"
    hosts: all
    connection: ssh
    become: yes

    vars_prompt:
      - name: nfs_ip
        prompt: "What is the IP address for the NFS server?"
        private: no
      - name: reconfig_network_response
        prompt: "Do you want the nodes to change to a seperate network (y/n)?"
        private: no
    
    tasks:
      - import_tasks: tasks/update.yaml
      - import_tasks: tasks/install-sys-utils.yaml
      - import_tasks: tasks/install-py-utils.yaml
      - import_tasks: tasks/hostname.yaml
      - import_tasks: tasks/testbed.yaml
      - import_tasks: tasks/setup.yaml
      - import_tasks: tasks/services.yaml
      - import_tasks: tasks/reboot.yaml
      - import_tasks: tasks/easy-rsa-stage-2.yaml
      # TODO: Collect all 10. addresses from participating Pi's for network reconfiguration.
      - import_tasks: tasks/openvpn.yaml
      - import_tasks: tasks/filesystem.yaml
      - import_tasks: tasks/reboot.yaml
