refresh:
	python3 -m ansible playbook refresh_playbook.yaml --ask-pass --ask-become-pass

install:
	python3 -m ansible playbook install_playbook.yaml --ask-pass --ask-become-pass

openvpn:
	python3 -m ansible playbook exchange_playbook.yaml --ask-pass --ask-become-pass