- name: "Creating easy-rsa CA directory"
  shell: make-cadir ./easy-rsa
  args:
    chdir: /etc/openvpn

- name: "Replacing vars file"
  copy:
    src: vars
    dest: /etc/openvpn/easy-rsa
    force: true

- name: "Initializing public key infrastructure"
  shell: ./easyrsa init-pki
  args:
    chdir: /etc/openvpn/easy-rsa

- name: "Building certificate authority"
  shell: ./easyrsa --batch build-ca nopass
  args:
    chdir: /etc/openvpn/easy-rsa

- name: "Generating server key"
  shell: "./easyrsa --batch gen-req {{ ansible_hostname }} nopass"
  args:
    chdir: /etc/openvpn/easy-rsa

- name: "Generating server Diffie Hellman parameters"
  shell: ./easyrsa --batch gen-dh
  args:
    chdir: /etc/openvpn/easy-rsa

- name: "Generating server certificate"
  shell: "./easyrsa --batch sign-req server {{ ansible_hostname }} nopass"
  args:
    chdir: /etc/openvpn/easy-rsa

- name: "Copying server keys and certificates to OpenVPN directory"
  shell: "cp pki/dh.pem pki/ca.crt pki/issued/{{ ansible_hostname }}.crt pki/private/{{ ansible_hostname }}.key /etc/openvpn"
  args:
    chdir: /etc/openvpn/easy-rsa
