- name: "Copying netplan bridge template file"
  copy:
    src: 00-installer-config.yaml
    dest: /etc/netplan
    force: true

- name: "Adding devices IP address"
  lineinfile:
    path: /etc/netplan/00-installer-config.yaml
    search_string: "INSERT_IP_HERE"
    line: "        - {{ ansible_default_ipv4.address }}/24"

- name: "Adding gateway address"
  lineinfile:
    path: /etc/netplan/00-installer-config.yaml
    search_string: "INSERT_GATEWAY_HERE"
    line: "      gateway4: {{ gateway_ip }}"

- name: "Applying new netplan configuration"
  shell:
    cmd: sudo netplan apply

- name: "Copying OpenVPN script"
  copy:
    src: openvpn_up
    dest: /etc/openvpn
    force: true
    mode: ugo+x

- name: "Copying server configuration file"
  copy:
    src: server.conf
    dest: "/etc/openvpn/{{ ansible_hostname }}.conf"
    force: true

- name: "Copying server key file to OpenVPN file"
  copy:
    src: /etc/openvpn/easy-rsa/pki/private/{{ ansible_hostname }}.key
    dest: /etc/openvpn/
    remote_src: true

- name: "Replacing server certificate filename"
  lineinfile:
    path: "/etc/openvpn/{{ ansible_hostname }}.conf"
    search_string: "cert server.crt"
    line: "cert {{ ansible_hostname }}.crt"

- name: "Replacing server key filename"
  lineinfile:
    path: "/etc/openvpn/{{ ansible_hostname }}.conf"
    search_string: "key server.key"
    line: "key {{ ansible_hostname }}.key"

- name: "Replacing Diffie Hellman parameter filename"
  lineinfile:
    path: "/etc/openvpn/{{ ansible_hostname }}.conf"
    search_string: "dh dh2048.pem"
    line: "dh dh.pem"

- name: "Generating TLS-authentication key"
  shell: openvpn --genkey --secret ta.key
  args:
    chdir: /etc/openvpn

- name: "Fetching TLS-auth key for third-party CA device"
  fetch:
    src: /etc/openvpn/ta.key
    dest: /etc/openvpn
    flat: true

- name: "Enabling IP forwarding"
  lineinfile:
    path: /etc/sysctl.conf
    search_string: "#net.ipv4.ip_forward=1"
    line: "net.ipv4.ip_forward=1"

- name: "Realoding sysctl"
  shell: sysctl -p /etc/sysctl.conf

- name: "Starting OpenVPN server daemon"
  shell: "systemctl start openvpn@{{ ansible_hostname }}"

- name: "Starting OpenVPN client daemon on third party"
  local_action:
    module: shell
    cmd: "sudo systemctl start openvpn@client"