---
  - name: "Configuring NFS server"
    hosts: all
    connection: ssh
    become: yes

    tasks:
      - import_tasks: tasks/update.yaml
      - import_tasks: tasks/install-sys-utils.yaml
      - import_tasks: tasks/filesystem.yaml
      - import_tasks: tasks/easy-rsa.yaml
      - import_tasks: tasks/openvpn.yaml