---
  - name: "Configuring NFS server"
    hosts: 127.0.0.1
    connection: localhost
    become: yes

    tasks:
      - import_tasks: tasks/update.yaml
      - import_tasks: tasks/install-sys-utils.yaml
      - import_tasks: tasks/filesystem.yaml
      - import_tasks: tasks/cluster.yaml
      - import_tasks: tasks/easy-rsa.yaml
      - import_tasks: tasks/openvpn.yaml