---
  - name: "Configuring NFS server"
    hosts: all
    connection: ssh
    become: yes

    vars_prompt:
      - name: gateway_ip
        prompt: "What is the gateway address?"
        private: no

    tasks:
      - import_tasks: tasks/update.yaml
      - import_tasks: tasks/install-sys-utils.yaml
      - import_tasks: tasks/filesystem.yaml
      - import_tasks: tasks/easy-rsa-stage-2.yaml
      - import_tasks: tasks/openvpn-stage-2.yaml
