- name: "Creating easy-rsa CA directory"
  shell: make-cadir ./easy-rsa
  args:
    chdir: /etc/openvpn

- name: "Replacing vars file"
  copy:
    src: vars
    dest: /etc/openvpn/easy-rsa
    force: true

- name: "Initializing public key infrastructure"
  shell: ./easyrsa init-pki
  args:
    chdir: /etc/openvpn/easy-rsa

- name: "Building certificate authority"
  shell: ./easyrsa --batch build-ca nopass
  args:
    chdir: /etc/openvpn/easy-rsa

- name: "Generating key and certificate request for the server"
  shell: "./easyrsa --batch gen-req {{ ansible_hostname }} nopass"
  args:
    chdir: /etc/openvpn/easy-rsa

- name: "Copying issued key to OpenVPN directory"
  shell: "cp easy-rsa/pki/private/{{ ansible_hostname }}.key ."
    args:
      chdir: /etc/openvpn