- name: "Installing utilities"
  apt:
    name: "{{ utils }}"

- name: "Installing Python utilities"
  apt:
    name: "{{ python3 }}"

- name: "Manually configuring Python virtual environment"
  shell:
    cmd: "python3.11 -m venv {{ lookup('env', 'HOME') }}/zipa-cluster-venv" 

- name: "Installing Python packages"
  pip:
    requirements: requirements.txt
    virtualenv: "{{ lookup('env', 'HOME') }}/zipa-cluster-venv"
  
- name: "Updating Python packages"
  shell:
    cmd: "{{ lookup('env', 'HOME') }}/zipa-cluster-venv/bin/poetry update"