- name: "Configuring Python virtual environment"
  shell:
    cmd: "python3.11 -m venv /home/pi/zipa-cluster-venv"

- name: "Copying requirements.txt file from host"
  copy:
    src: requirements.txt
    dest: "/home/pi/zipa-cluster-venv"

- name: "Installing Python packages"
  pip:
    requirements: "/home/pi/zipa-cluster-venv/requirements.txt"
    virtualenv: "/home/pi/zipa-cluster-venv"