- name: "Copying client configuration file"
  copy:
    src: client.conf
    dest: /etc/openvpn
    force: true

- name: "Replacing certificate name in client configuration file"
  lineinfile:
    path: /etc/openvpn/client.conf
    search_string: "cert client.crt"
    line: "cert {{ ansible_hostname }}.crt"

- name: "Replacing key name in client configuration file"
  lineinfile:
    path: /etc/openvpn/client.conf
    search_string: "key client.key"
    line: "key {{ ansible_hostname }}.key"

