- name: "Sending network.sh over"
  copy:
    src: network.sh
    dest: "~"

- name: "Sending network configuration over"
  copy:
    src: network.nmconnection
    dest: /etc/NetworkManager/system-connections/

- name: Changing network.sh permissions
  ansible.builtin.file:
    path: ~/network.sh
    owner: root
    group: root
    mode: '600'

- name: Creating job to reconfigure network
  ansible.builtin.cron:
    name: "running network.sh"
    special_time: reboot
    job: "~/network.sh"