- name: "Sending network configuration over"
  copy:
    src: network.nmconnection
    dest: /etc/NetworkManager/system-connections/

- name: "Changing permissions for network configuration file"
  file:
    path: /etc/NetworkManager/system-connections/network.nmconnection
    owner: root
    group: root
    mode: '600'

- name: "Switching wireless networks"
  shell: sudo nmcli c reload; sudo nmcli con down preconfigured; sudo nmcli con up network;