- name: "Starting avahi"
  systemd:
    name: avahi-daemon
    enabled: true
    force: true
    state: restarted

- name: "Placing ZIPA service file"
  copy:
    src: zipa.service
    dest: /etc/avahi/services