- name: "Deleting testbed code"
  file:
    state: absent
    path: /home/pi/zipa-testbed

- name: "Cloning testbed"
  git:
    repo: 'https://github.com/isaac-ahlgren/zipa-testbed'
    dest: "/home/pi/zipa-testbed"

- name: "Changing permissions on zipa-testbed directory"
  shell: chmod ugo+w zipa-testbed
  args:
    chdir: /home/pi/

- name: "Changing permissions on zipa-testbed files"
  shell: chmod ugo+w *
  args:
    chdir: /home/pi/zipa-testbed/

- name: "Replacing host IP address in zipa_sys.py"
  replace:
    path: "/home/pi/zipa-testbed/src/zipa_sys.py"
    regexp: 'DEVICE IDENTIFIER'
    replace: "{{ ansible_facts['tap0']['ipv4']['address'] }}"

- name: "Compiling RS Code"
  shell: make all
  args:
    chdir: /home/pi/zipa-testbed/lib/rscode-1.3/

- name: "fill in user information"
  vars:
    user: user
  lineinfile: 
    path: '/home/pi/zipa-testbed/src/zipa_sys.py'
    regexp: 'user=.*'
    line: "            user='{{ user }}',"

- name: "fill in password information"
  vars:
    password: password
  lineinfile: 
    path: '/home/pi/zipa-testbed/src/zipa_sys.py'
    regexp: 'password=.*'
    line: "            password='{{ password }}',"