- name: "Cloning testbed"
  git:
    repo: 'https://github.com/isaac-ahlgren/zipa-testbed'
    dest: "/home/pi/zipa-testbed"
    version: id-fix

- name: "Replacing host IP address"
  replace:
    path: "/home/pi/zipa-testbed/main.py"
    regexp: 'eth0'
    replace: "{{ ansible_default_ipv4.interface }}"

- name: "Replacing NFS mount point"
  replace:
    path: "/home/pi/zipa-testbed/main.py"
    regexp: '/mnt/data'
    replace: "/mnt/dryrun" # Change to NFS directory