- name: "Creating local file for tun0 addresses"
  local_action:
    module: file
    path: /etc/openvpn/client-openvpn-addresses
    state: touch
    mode: '0644'

- name: "Appending OpenVPN tun0 addresses for optional network reconfiguration"
  local_action:
    module: shell
    cmd: "echo {{ ansible_facts['tap0']['ipv4']['address'] }} >> client-openvpn-addresses"
    args:
      chdir: /etc/openvpn
 