---
  - name: "Configuring this device as the CA authority"
    hosts: localhost
    connection: localhost
    become: yes

    vars_prompt:
    - name: server_ip
      prompt: "What is the IP address of the server?"
      private: false

    tasks:
      - import_tasks: tasks/update.yaml
      - import_tasks: tasks/install-sys-utils.yaml
      - import_tasks: tasks/easy-rsa.yaml
      - import_tasks: tasks/openvpn.yaml