network:
  version: 2
  ethernets:
    ens160:
      dhcp4: false
      addresses:
        - INSERT_IP_HERE
      gateway4: INSERT_GATEWAY_HERE
      nameservers:
        addresses:
          - 8.8.8.8
  bridges:
    br0:
      dhcp4: false
      addresses: 
        - 10.0.0.2/24
      gateway4: 10.0.0.1
      nameservers:
        addresses:
          - 10.0.0.1
